import path from "node:path";
import { writeFile } from "../utils/index.js";
import type {
	MigrateOptions,
	MigrationManifest,
	MigrationResult,
} from "./types.js";

/**
 * Generates MIGRATION_REPORT.md with a summary of what was converted,
 * what needs manual attention, and next steps.
 */
export async function generateReport(
	manifest: MigrationManifest,
	options: MigrateOptions,
	targetDir: string,
	result: MigrationResult,
): Promise<void> {
	const lines: string[] = [];

	lines.push("# Migration Report");
	lines.push("");
	lines.push(
		`> Generated by forge migrate on ${new Date().toISOString().split("T")[0]}`,
	);
	lines.push(`> Source: \`${manifest.sourceDir}\``);
	lines.push("");

	// Summary
	lines.push("## Summary");
	lines.push("");
	lines.push("| Item | Count |");
	lines.push("| --- | --- |");
	lines.push(`| API Routes Converted | ${result.routesConverted} |`);
	lines.push(`| Pages Converted | ${result.pagesConverted} |`);
	lines.push(`| Components Copied | ${result.componentsCopied} |`);
	lines.push(`| Files Written | ${result.filesWritten.length} |`);
	lines.push(`| Auth Type | ${options.auth} |`);
	lines.push(`| Database Type | ${options.db} |`);
	lines.push("");

	// Replit config
	if (manifest.replitConfig) {
		lines.push("## Replit Configuration (Source)");
		lines.push("");
		lines.push("The source app used the following Replit integrations:");
		lines.push("");
		for (const integration of manifest.replitConfig.integrations) {
			lines.push(`- \`${integration}\``);
		}
		lines.push("");
		lines.push(`Modules: ${manifest.replitConfig.modules.join(", ")}`);
		lines.push(`Port: ${manifest.replitConfig.port}`);
		lines.push("");
	}

	// Replit-specific files excluded
	lines.push("## Replit-Specific Files (Excluded)");
	lines.push("");
	lines.push(
		"The following Replit-specific files were NOT copied to the target:",
	);
	lines.push("");
	lines.push("| File | Purpose | Replacement |");
	lines.push("| --- | --- | --- |");
	lines.push(
		"| `.replit` | Replit IDE/runtime config | N/A (Next.js uses next.config.ts) |",
	);
	lines.push(
		`| \`server/replit_integrations/auth/\` | Replit OIDC auth | Replaced by ${options.auth} auth |`,
	);
	lines.push(
		"| `server/replit_integrations/object_storage/` | Replit object storage | Manual setup needed |",
	);
	lines.push(
		"| `server/vite.ts` | Vite dev server for Express | Next.js dev server |",
	);
	lines.push(
		"| `server/static.ts` | Static file serving | Next.js handles this |",
	);
	lines.push("| `vite.config.ts` | Vite build config | next.config.ts |");
	lines.push("| `client/index.html` | Vite SPA entry | Next.js App Router |");
	lines.push(
		"| `client/src/main.tsx` | React createRoot entry | Next.js App Router |",
	);
	lines.push("| `script/build.ts` | Custom esbuild build | next build |");
	lines.push("");

	// Dependencies removed
	if (
		manifest.replitDependencies.length > 0 ||
		manifest.serverDependencies.length > 0
	) {
		lines.push("## Dependencies Removed");
		lines.push("");
		if (manifest.replitDependencies.length > 0) {
			lines.push("**Replit-specific:**");
			for (const dep of manifest.replitDependencies) {
				lines.push(`- \`${dep}\``);
			}
			lines.push("");
		}
		if (manifest.serverDependencies.length > 0) {
			lines.push("**Express/Vite server (replaced by Next.js):**");
			for (const dep of manifest.serverDependencies) {
				lines.push(`- \`${dep}\``);
			}
			lines.push("");
		}
	}

	// Routes needing manual review
	if (result.routesNeedingReview.length > 0) {
		lines.push("## Routes Needing Manual Review");
		lines.push("");
		lines.push(
			"These routes were converted but contain patterns that may need adjustment:",
		);
		lines.push("");
		for (const route of result.routesNeedingReview) {
			lines.push(`- ${route}`);
		}
		lines.push("");
	}

	// Components flagged
	if (result.componentsFlagged.length > 0) {
		lines.push("## Components Needing Attention");
		lines.push("");
		lines.push(
			"These files reference Replit-specific APIs and need manual updates:",
		);
		lines.push("");
		for (const comp of result.componentsFlagged) {
			lines.push(`- ${comp}`);
		}
		lines.push("");
	}

	// Warnings
	if (result.warnings.length > 0 || manifest.warnings.length > 0) {
		lines.push("## Warnings");
		lines.push("");
		for (const w of [...manifest.warnings, ...result.warnings]) {
			lines.push(`- ${w}`);
		}
		lines.push("");
	}

	// Next steps
	lines.push("## Next Steps");
	lines.push("");
	lines.push("1. **Environment Setup**");
	lines.push("   - Copy `.env.example` to `.env.local`");
	lines.push(
		"   - Configure `DATABASE_URL` to point to your Supabase or local PostgreSQL",
	);
	if (options.auth === "workos") {
		lines.push(
			"   - Set `WORKOS_CLIENT_ID`, `WORKOS_API_KEY`, and `WORKOS_COOKIE_PASSWORD`",
		);
	}
	lines.push("");
	lines.push("2. **Database Migration**");
	lines.push("   - Review the schema in `db/schema.ts`");
	lines.push("   - Run `pnpm db:push` to push the schema to your database");
	lines.push(
		"   - Or run `pnpm db:generate` then `pnpm db:migrate` for migration files",
	);
	lines.push("");
	lines.push("3. **Manual Review**");
	lines.push(
		"   - Review routes flagged above for complex patterns (file uploads, streaming)",
	);
	lines.push("   - Review components flagged for Replit-specific API usage");
	lines.push("   - Update any hardcoded URLs or port references");
	lines.push("   - Test authentication flow end-to-end");
	lines.push("");
	lines.push("4. **Run Locally**");
	lines.push("   ```bash");
	lines.push("   pnpm install");
	lines.push("   pnpm dev");
	lines.push("   ```");
	lines.push("");

	const reportContent = lines.join("\n");
	await writeFile(path.join(targetDir, "MIGRATION_REPORT.md"), reportContent);
	result.filesWritten.push("MIGRATION_REPORT.md");
}
