export function generateCursorProjectContextRule(
	isMonorepo: boolean,
	hasDatabase: boolean,
): string {
	const monorepoNotes = isMonorepo
		? "- This project is a monorepo. Run commands from the repository root unless a command explicitly targets a subdirectory."
		: "- This project is standalone. Run commands from the repository root.";
	const dbNotes = hasDatabase
		? "- Database support is enabled. Schema and database utilities are in `db/`."
		: "- No database was scaffolded. Add database files only if the user requests them.";

	return `---
description: Project-specific context for this generated app
alwaysApply: true
---

# Project Context

- This app was generated by Forge.
- Use pnpm for package management and scripts.
${monorepoNotes}
${dbNotes}
- Use ESLint for linting and Biome for formatting.
- Prefer editing existing files over creating duplicate alternatives.
`;
}
